version: '2'
services:
  postgres:
    image: 'postgres:9.6.2-alpine'
    restart: 'always'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
  redis:
    image: 'redis:3.2.8-alpine'
    command: redis-server --requirepass redisuser
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  geolocation:
    image: 'xjensen/freegeoip'
    restart: 'always'
    ports:
      - '8080:8080'
  rails:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    expose:
      - '3000'
    volumes:
      - '.:/raptmap'
    env_file:
      - '.env'
  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/raptmap'
    env_file:
      - '.env'
  nginx:
    build:
      context: .
      dockerfile: config/containers/nginx/Dockerfile-nginx-dev
    links:
      - rails
    ports:
      - "3000:80"
      - "3443:443"
    volumes:
      - './public:/raptmap/public'
volumes:
  redis:
  postgres:
