import React from 'react';
import { connect } from 'react-redux';
import { AutoForm, autoDispatchersByModel } from './AutoForm.jsx'

// LocationForm is a form field that allows the user to change
// the map's location by typing it in. Yay, geolocation!

// See ../ForwWidget.jsx for an explanation of mapStateToProps,
// mapDispatchToProps, and the connect() function that appears
// at bottom.

const mapStateToProps = function(store) {
  return store.location.live
};

const mapDispatchToProps = function(dispatch, ownProps) {
  // Here we combine our local dispatch functions with the functions
  // generated by autoDispatchersByModel() in ./AutoForm.jsx.
  return Object.assign({
    // commitValues() is called by handleSubmit() in AutoForm.
    commitValues: function(value, suggestionObject) {
      dispatch({
        type: 'CHANGE_ALL',
        location: {
          name: value,
          latitude: (suggestionObject.latitude ? suggestionObject.latitude : null),
          longitude: (suggestionObject.longitude ? suggestionObject.longitude : null),
        },
        // RadiusForm will be displayed next, so tell the store that
        // it has been revealed to the user.
        radius: {
          revealed: true
        },
        // User is done with location, so we display the RadiusForm.
        // That's step 3.
        step: 3
      })
    }
  }, autoDispatchersByModel(dispatch, "location"))
}

// All the heavy lifting is done in AutoForm, so all we need from React
// here is a "functional" component.
// https://facebook.github.io/react/docs/components-and-props.html
function LocationForm(props) {
  return (
    <div className="location-form">
      <p className="field-prompt">
        Find fellow enthusiasts near:
      </p>
      <AutoForm url='/locations/autocomplete?query='
                warning="Please add a location"
                placeholder="e.g., Fremont, CA, USA"
                {...props} />
    </div>
  );
};

export default connect(mapStateToProps, mapDispatchToProps)(LocationForm);
