import React from 'react';
import { connect } from 'react-redux';
import { AutoForm, autoDispatchersByModel } from './AutoForm.jsx'

// TopicForm allows the user to enter a desired search topic.

// See ../ForwWidget.jsx for an explanation of mapStateToProps,
// mapDispatchToProps, and the connect() function that appears
// at bottom.

const mapStateToProps = function(store) {
  return store.topic.live;
}

const mapDispatchToProps = function(dispatch, ownProps) {
  // Here we combine our local dispatch functions with the functions
  // generated by autoDispatchersByModel() in ./AutoForm.jsx.
  return Object.assign({
    // suggestionObject isn't needed here but it's part of what gets
    // sent to commitValues() by handleSubmit() in AutoForm.
    commitValues: function(value, suggestionObject) {
      dispatch({
        type: 'CHANGE_ALL',
        topic: {
          name: value
        },
        // LocationForm will be displayed next, so tell the store that
        // it has been revealed to the user.
        location: {
          revealed: true
        },
        // User is done with topic, so we display the LocationForm.
        // That's step 2.
        step: 2
      });
    }
  }, autoDispatchersByModel(dispatch, "topic"))
}

// All the heavy lifting is done in AutoForm, so all we need from React
// here is a "functional" component.
// https://facebook.github.io/react/docs/components-and-props.html
function TopicForm(props) {
  return (
    <div className="topic-form">
      <p className="field-prompt">
        Find people interested in:
      </p>
      <AutoForm url='/topics/autocomplete?query='
                placeholder="e.g., Basketball, Knitting, Mah Jong, etc."
                warning="Please add a topic"
                {...props} />
    </div>
  )
}

export default connect(mapStateToProps, mapDispatchToProps)(TopicForm);
