FROM nginx:1.11.9-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash openssh apache2-utils

ENV RAILS_ROOT /raptmap

WORKDIR $RAILS_ROOT

RUN mkdir log

COPY public public/

COPY config/containers/nginx/ssl ssl/

COPY config/containers/nginx/raptmap-prod.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
